# Generated by Django 2.0.7 on 2018-08-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('describe', models.CharField(default='', max_length=500)),
                ('recommend', models.CharField(default='***', max_length=5)),
                ('bReward', models.BooleanField(default=False)),
                ('reward', models.IntegerField(default=200)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('identification', models.CharField(default='', max_length=18)),
                ('age', models.IntegerField(default=20)),
                ('location', models.TextField(default='', max_length=255)),
                ('describe', models.CharField(default='', max_length=500)),
                ('agent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Agent')),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
    ]
