# Generated by Django 2.0.7 on 2018-08-15 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('age', models.IntegerField(default=18)),
                ('identification', models.CharField(blank=True, max_length=18)),
                ('record', models.CharField(choices=[('gaozhong', '高中'), ('xiaoxue', '小学'), ('chuzhong', '初中'), ('dazhuan', '大专'), ('zhongzhuan', '中专')], max_length=100)),
                ('targetCollege', models.CharField(choices=[('dalian', '大连理工大学'), ('dongbei', '东北大学'), ('kuangda', '中国矿业大学'), ('changsha', '长沙医学院'), ('hunan', '湖南医药学院')], max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('professional', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('describe', models.CharField(default='', max_length=500)),
                ('recommend', models.CharField(default='***', max_length=5)),
                ('bReward', models.BooleanField(default=False)),
                ('reward', models.IntegerField(default=200)),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bDeleted', models.BooleanField(auto_created=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('identification', models.CharField(default='', max_length=18)),
                ('age', models.IntegerField(default=20)),
                ('location', models.TextField(default='', max_length=255)),
                ('describe', models.CharField(default='', max_length=500)),
                ('agent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Agent')),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
    ]
