# Generated by Django 2.0.7 on 2018-08-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ('created_time',)},
        ),
        migrations.AddField(
            model_name='agent',
            name='bDeleted',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='bDeleted',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='bDeleted',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Agent'),
        ),
    ]
