# Generated by Django 2.0.7 on 2018-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180803_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='reward',
            field=models.IntegerField(default=200),
        ),
    ]
